"""add zalo_bot_id to users

Revision ID: 5bad8188c497
Revises: 745d0d76d03d
Create Date: 2026-03-11 03:38:57.327639
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5bad8188c497'
down_revision: Union[str, None] = '745d0d76d03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zalo_bot_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_zalo_bot_id'), 'users', ['zalo_bot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_zalo_bot_id'), table_name='users')
    op.drop_column('users', 'zalo_bot_id')
    # ### end Alembic commands ###
